import type { Metadata } from 'next';
import './globals.css';
import { Inter, Great_Vibes } from 'next/font/google';
import Footer from '@/components/footer';

export const greatVibes = Great_Vibes({
    subsets: ['latin'],
    weight: ['400'], 
});

export const inter = Inter({
    subsets: ['latin'], // Latin subset
    weight: ['400', '700'], //specific font weights
});

export const metadata: Metadata = {
    title: 'Foodtuck',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-bg">
                {children}
                <Footer />
            </body>
        </html>
    );
}
